# Config file for automatic testing at travis-ci.org
language: python

branches:
  only:
    - master

jobs:
  fast_finish: true
  include:
    - env:
        - TOXENV=docs
        - READTHEDOCS=true
      name: "Documentation"
      python: 3.6
    - env: TOXENV=black
      name: "Black and flake8 compliance"
      python: 3.6
    - env: TOXENV=py38
      name: "Python3.8 (Linux)"
      python: 3.8
    - env: TOXENV=py37
      name: "Python3.7 (Linux)"
      python: 3.7
    - env: TOXENV=py36
      name: "Python3.6 (Linux)"
      python: 3.6


before_install:
    - printenv
    - pip install --upgrade pip

install:
    - pip install -U tox-travis

script: tox -e $TOXENV

